### ISSUE TITLE
Stable version on packagist

### ISSUE THREAD

**Issue by webberig** [AppVentus/AsseticInjectorBundle#7]
Hi,

I've added a dependancy to this package in one of my bundles. (https://packagist.org/packages/concerto-cms/admin-bundle). But your package is not being installed because it has no stable version.

Could you create a release with a version number for this package ? This will give the package a stable state on packagist and allow bundles to refer to this package.

**Comment by paulandrieux** [comment]
Hi Webberig,
I created the 1.0.0 release.

**Comment by webberig** [comment]
Thanks!
